using AdventOfCode24.Day08;
using JetBrains.Annotations;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace AdventOfCode24.Tests.Day08;

[TestClass]
[TestSubject(typeof(FrequencyAntiNodes))]
public class FrequencyAntiNodesTest
{
    private const string ExampleInput = """
                                        ............
                                        ........0...
                                        .....0......
                                        .......0....
                                        ....0.......
                                        ......A.....
                                        ............
                                        ............
                                        ........A...
                                        .........A..
                                        ............
                                        ............
                                        """;


    [TestMethod]
    public void CountFrequencyAntiNodes_ExampleInput_ShouldReturnCorrectResult()
    {
        var count = FrequencyAntiNodes.CountFrequencyAntiNodes(ExampleInput);

        Assert.AreEqual(14, count);
    }
}